## NumPy 是什么？

NumPy是使用Python进行科学计算的基础软件包。除其他外，它包括：

* 功能强大的N维数组对象。
* 精密广播功能函数。
* 集成 C/C+和Fortran 代码的工具。
* 强大的线性代数、傅立叶变换和随机数功能。

导入 NumPy

In [3]:
import numpy as np

查看 NumPy 版本信息

In [4]:
print(np.__version__)

1.16.4


### 创建数组
NumPy 的主要对象是多维数组 Ndarray。在 NumPy 中维度（dimensions）叫做轴（axes），轴的个数叫做秩（rank）。

例如，下方数组是一个秩为 1 的数组，因为它只有一个轴，而轴的长度为 3。

In [5]:
[1, 2, 3]

[1, 2, 3]

又例如，下方数组的秩为 2。第一个维度长度为 2,第二个维度长度为 3。

In [6]:
[[1., 2., 3.],
 [4., 5., 6.]]

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

#### 通过列表创建一维数组

In [7]:
np.array([1,2,3])

array([1, 2, 3])

#### 通过列表创建二维数组

In [8]:
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

#### 创建全为 0 的二维数组

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 创建全为 1 的三维数组

In [10]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### 创建一维等差数组

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### 创建二维等差数组

In [12]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

#### 创建单位矩阵（二维数组）

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 创建等间隔一维数组

In [14]:
np.linspace(1, 10, num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

#### 创建二维随机数组

In [15]:
np.random.rand(2, 3)

array([[0.17455677, 0.67618189, 0.90588316],
       [0.0970564 , 0.05278913, 0.83639074]])

#### 创建二维随机整数数组（数值小于 5）

In [20]:
np.random.randint(5, size=(2, 3))

array([[4, 2, 2],
       [3, 3, 1]])

#### 依据自定义函数创建数组

In [21]:
np.fromfunction(lambda i, j: i + j, (3, 3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

### 数组运算

#### 生成一维示例数组

In [22]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(1, 6)
a, b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

#### 一维数组运算

In [23]:
a + b

array([11, 22, 33, 44, 55])

In [24]:
a - b

array([ 9, 18, 27, 36, 45])

In [25]:
a * b

array([ 10,  40,  90, 160, 250])

In [26]:
a / b

array([10., 10., 10., 10., 10.])

#### 生成二维示例数组（可以看作矩阵）

In [28]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
A, B

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

#### 矩阵运算

In [29]:
A + B

array([[ 6,  8],
       [10, 12]])

In [30]:
A - B

array([[-4, -4],
       [-4, -4]])

In [33]:
# 矩阵元素间乘法运算
A * B

array([[ 5, 12],
       [21, 32]])

In [34]:
# 矩阵乘法运算
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [35]:
# 如果使用 np.mat 将二维数组准确定义为矩阵，就可以直接使用 * 完成矩阵乘法计算
np.mat(A) * np.mat(B)

matrix([[19, 22],
        [43, 50]])

In [36]:
2 * A

array([[2, 4],
       [6, 8]])

In [39]:
# 矩阵的转置
A.T

array([[1, 3],
       [2, 4]])

In [40]:
# 矩阵求逆
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 数组切片和索引

#### 一维数组索引

In [41]:
a = np.array([1, 2, 3, 4, 5])
a[0], a[-1]

(1, 5)

#### 一维数组切片

In [42]:
a[0:2], a[:-1]

(array([1, 2]), array([1, 2, 3, 4]))

####  二维数组索引

In [43]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
a[0], a[-1]

(array([1, 2, 3]), array([7, 8, 9]))

#### 二维数组切片（取第 2 列）

In [44]:
print(a)

a[:, 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

In [45]:
# 二维数组切片（取第 2，3 行）
a[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])